### ISSUE TITLE
Setup dev environment

### ISSUE THREAD

**Issue by petarov** [petarov/myglob#21]
Дискусия относно development requirements & setup.

## Инструменти

  * Java JRE/JDK 1.6+

## Среда

1. Setup на средата за работа в Eclipse (Eclipse IDE for Java Developers върши работа). Инсталация на [ADT plugin-ът](http://developer.android.com/sdk/installing/installing-adt.html).

2. Fork на [проекта от Github](https://github.com/petarov/myglob) в собствено repository и клониране в работна среда (workspace-a).

3. Import на проекта в Eclipse и конфигурация на зависимостите.

*Eclipse -> File -> Import -> Existing Android Project ...*

![screen shot 2015-05-09 at 13 02 19 1](https://cloud.githubusercontent.com/assets/547597/7549918/c6e85730-f64b-11e4-83e5-f2fd5cd9a2aa.png)

## Зависимости

Android Target SDK. В момента целевото API, коeто трябва да бъде инсталиранo е API 15. (Това най-вероятно ще се промени на 22 по-късно).

*Eclipse -> Window -> Android SDK Manager*

![screen shot 2015-05-09 at 13 05 51](https://cloud.githubusercontent.com/assets/547597/7549932/5797d972-f64c-11e4-932d-c677d9fe4d28.png)

## Deploy & Test

1. Emulator

Android emulator-ът е твърде бавен за нормална работа. Безплатната версия на [Genymotion](https://www.genymotion.com/#!/store) решава този проблем.

След инсталация, трябва да се добави ново виртуално устройство.

![screen shot 2015-05-11 at 18 00 12](https://cloud.githubusercontent.com/assets/547597/7569225/9bfb9100-f807-11e4-9af6-da41257b46a7.png)

![screen shot 2015-05-11 at 17 59 57](https://cloud.githubusercontent.com/assets/547597/7569231/a890c19c-f807-11e4-86a6-1e53cb8b1f88.png)

2. Deploy

Genymotion трябва да е стартиран и да има пусната Android Virtual Machine.

*Eclipse -> Run Configurations -> Android Application* като за *Project* слагаме *myglob*.

*Run*, за да стартираме приложението в Genymotion.

**Comment by Tsvetoslav88** [comment]
Здравей,

Напарвих нещата, които си описал по-горе, но имам следните проблеми:
1) След като заредя проекта ми дава проблем с библиотеките:
- com.actionbarsherlock
- android.support
- R cannot be resolved to a variable
- net.vexelon.myglob.R
2) Като дам Import->Existing Maven project ми дава: A resource exists with a different case: '/ActionBarSherlock'.

Поздрави,
Цецо

**Comment by petarov** [comment]
Здравей Цецо,
Настройката на ActionBarSherlock е наистина tricky заради повтарящите се имена. Ще погледна днес как беше при мен и ще ти дам feedback тук.

Между другото една от целите е по-нататък да разкараме ActionBarSherlock за сметка AppCompat. :wink:

**Comment by Tsvetoslav88** [comment]
Здравей,

Ще очаквам да ми пратиш как да си направя настройката, за да си импортирам правилно ActionBarSherlock. Относно 1-ят проблем, който ти описах с библиотеките, дали ще може да ми ги сложиш някъде, за да мога да си ги импортирам(по-горе в комуникацията съм ти ги описал, кои са ми проблемните)?

Поздрави,
Цецо

**Comment by petarov** [comment]
Привет,

Реших да улесня нещата, тъй като ActionBarSherlock е твърде стара библиотека и неминуемо създава проблеми. Компилирах самата библиотека и добавих всички зависимости в [libs](libs).

Пусни един `git pull origin`, за да обновиш и виж дали всичко ще е наред в Eclipse-a и дали има останали build errors някакви.

**Comment by Tsvetoslav88** [comment]
Здравей,

Клонирах си отново проекта(myglob) от репозиторито и сега изглежда всичко да е наред(няма build errors). Сега има ли нужда да си добавя Maven проекта ActionBarSherlock, ако не какви са последващите стъпки? :)

Поздрави.

**Comment by petarov** [comment]
Супер! :) Значи сме на финала. 

Следва да инсталираш Genymotion emulator-a (виж заглавния post по-горе) и да deploy-неш приложението. 

След като пуснеш GM, би следвало да можеш да deploy-неш от Eclipse -> Run As -> Android Application. Eclipse трябва да изведе прозорец, в който избираш emulator-a и вече самото приложение дефакто управляваш от GM.

**Comment by Tsvetoslav88** [comment]
Здравей,

Инсталирах си genymotion+ Oracle VM, след което си добавих виртуално устройство(същото, като от printscreen по-горе). След като отидах в Eclipse да deploy-на проекта видях, че ми дава грешки, които до вчера ги нямаше. Имаш ли на представа, защо се получавам, дане би да работиш по него и на мен да се отразява, защото гледам съм вързан с репозиторито.

![error](https://cloud.githubusercontent.com/assets/8929789/7595822/13532ed0-f8f2-11e4-95a5-3b8293a794cd.jpg)

**Comment by petarov** [comment]
Привет,

Не, освен ако не дърпаш последният state с `git pull` няма как да се отразят каквито и да било промени от моята среда при теб.

Относно грешките - това може би е Lint проблем (статичен анализ на кода). Обикновено го изключвам при мен. Махни отметката на `When saving files, check for errors.`, и след това rebuild проекта - *Eclipse -> Project -> Clean*.

![screen shot 2015-05-12 at 22 32 46](https://cloud.githubusercontent.com/assets/547597/7597923/2b27d150-f8f7-11e4-8cf5-4d8b082cc162.png)

Ако все още има проблеми, виж какво казва tooltip-a в Eclipse. *Пример:*

![screen shot 2015-05-12 at 22 33 09](https://cloud.githubusercontent.com/assets/547597/7597953/66a3d0bc-f8f7-11e4-9b27-630f2b1c9c5d.png)

**Comment by petarov** [comment]
Още нещо. Сигурен ли си, че проектът е импортиран от:

*Eclipse -> File -> Import -> Existing Android Project ...*

Забелязах *JRE System Library* в screenshot-a, а мисля че не би трябвало да го има при Android project. При мен *Right Click -> Properties* показва следното:

![screen shot 2015-05-12 at 22 42 09](https://cloud.githubusercontent.com/assets/547597/7598065/36a6466e-f8f8-11e4-8cdf-9bd28c204830.png)

**Comment by Tsvetoslav88** [comment]
Здравей,

Проблема с проекта го преодолях :), но сега имам проблеми със стартирането на Genymotion. Пробвах да стартирам виртуалното устройство, при което след извесно време ми даде:
![errorvd](https://cloud.githubusercontent.com/assets/8929789/7638890/ae9d84aa-fa80-11e4-80ea-d32b7dc5d469.png) (до колкото видях от клипа, трябваше др. да се получи :))
След което си рестартирах компа, защото видях, че имам Update, при което направих нов опит, но този път ми се показа друга грешка:
![error2vd](https://cloud.githubusercontent.com/assets/8929789/7638901/de6cf36e-fa80-11e4-9aac-cef1fdc877b9.png)
 Чудя се дали не е добре да си разменим Skype-те, за да може да се чуваме и да предвижим конфигурационните проблеми по-бързо и да преминем към практическата част :)?

Поздрави!

**Comment by petarov** [comment]
Привет Цецо,

Тук ще ми е трудно да помогна, тъй като почти не използвам Windows и не съм срещал този проблем. Да не би да става въпрос за антивирус или firewall guard? Ако да, може би трябва да го изкл. по време на инсталация или пък да маркираш genymotion процеса като безопасен.

скайпът ми е като в бгдев форума.

**Comment by Tsvetoslav88** [comment]
Здравей,

Инсталирането на genymotion беше успешно. За проблемът с IP-то очевидно трябва да направя някакви конфигурационни настрайки, за проблемът с player.exe ме притеснява, че може да има проблеми с драйвера за видеото(тези неща успях да видя снощи но нямах достатъчно време). Очевидно ще трябва да отделя повече време, защото без него няма как да продължа(ако ти не може да ми предложиш аналогично решение :)). През почивните дни ще съм по-свободен и ще гледам да се позанимавам повече с това, като тогава ще те добавя в Skype, за да може да си комуникираме по-лесно(real time, когато си на линия). Ако се сещаш нещо, което мога да направя, докато се боря с тези проблеми може да ми драснеш(по проекта или нещо др.)?

Поздрави!

**Comment by petarov** [comment]
Ок. Може би иска някакви video drivers update, ако е вярно каквото [пише тук](http://w3facility.org/question/genymotion-player-exe-sttoped-working/). 

Алтернативите са две:
  1. Да тестваш с Андроид емулатора. Можеш да създадеш ново устройство от AVD Manager-a в Eclipse. След това като даваш *Run As* на проекта мисля, че можеш да избереш емулатор от AVD списъка.
  2. Да тестваш директно на Андроид устройство, ако разполагаш. Това по-принцип е най-добрият вариант.

**Comment by Tsvetoslav88** [comment]
Здравей.

Въпреки, че с Genymotion emulator-a нямам много напредък, реших да ти пиша, за да ти кажа какво съм направил и до къде съм стигнал :). Както ми препоръча в точка 1, добавих си в Eclipse genymotion и от него си създадох ново виртуално устройство. След като го стартирах отново се натъкнах на същата грешка.
![error1](https://cloud.githubusercontent.com/assets/8929789/7671628/16aa543a-fce1-11e4-84c0-76ac6dc41457.jpg)
Забелязах, че през Virtual Box, като го стартирам ми го зарежда без проблеми(но не и през genymotion) :
![virtualbox](https://cloud.githubusercontent.com/assets/8929789/7671653/f90f4d12-fce1-11e4-8d4c-93d5ead86eda.jpg)

Преди да го пусна виртуалното устройство от Virtual box, когато се опитам да стартирам проекта от Eclipse ми даваше:
"[2015-05-17 21:52:40 - myglob] ------------------------------
[2015-05-17 21:52:40 - myglob] Android Launch!
[2015-05-17 21:52:40 - myglob] adb is running normally.
[2015-05-17 21:52:40 - myglob] Performing net.vexelon.myglob.MainActivity activity launch
[2015-05-17 21:52:43 - myglob] Automatic Target Mode: using device '192.168.56.101:5555'
[2015-05-17 21:52:43 - myglob] Uploading myglob.apk onto device '192.168.56.101:5555'
[2015-05-17 21:52:44 - myglob] Installing myglob.apk...
[2015-05-17 21:52:46 - myglob] Installation error: Unknown failure
[2015-05-17 21:52:46 - myglob] Please check logcat output for more details.
[2015-05-17 21:52:46 - myglob] Launch canceled!"
, а след като го старитрах от VB:
"[2015-05-17 22:11:57 - myglob] ------------------------------
[2015-05-17 22:11:57 - myglob] Android Launch!
[2015-05-17 22:11:57 - myglob] adb is running normally.
[2015-05-17 22:11:58 - myglob] Performing net.vexelon.myglob.MainActivity activity launch
[2015-05-17 22:11:58 - myglob] Automatic Target Mode: using device '192.168.56.102:5555'
[2015-05-17 22:11:58 - myglob] Uploading myglob.apk onto device '192.168.56.102:5555'
[2015-05-17 22:11:58 - myglob] Failed to install myglob.apk on device '192.168.56.102:5555': EOF
[2015-05-17 22:11:58 - myglob] java.io.IOException: EOF
[2015-05-17 22:11:58 - myglob] Launch canceled!"
Някаква идея?
Как предлагаш да продъжа?

Поздрави!

**Comment by petarov** [comment]
Здравей,

Както написах по-горе вариантите, за които се сещам на този етап са или да пробваш да пуснеш приложението през стандарния Андроид емулатор, или диркетно на устройство.

За емулатора трябва да създадеш ново AVD устройство от AVD Manager-a. (Иконката в Eclipse).

![screen shot 2015-05-18 at 13 54 44](https://cloud.githubusercontent.com/assets/547597/7680316/75b981ec-fd65-11e4-9363-044a2f6c44d0.png)


![screen shot 2015-05-18 at 13 36 00](https://cloud.githubusercontent.com/assets/547597/7680307/656fd048-fd65-11e4-8df2-43a4e371105c.png)

![screen shot 2015-05-18 at 13 36 20](https://cloud.githubusercontent.com/assets/547597/7680320/7c10979c-fd65-11e4-95da-285333e5df7c.png)

Накрая стартираш приложението от *Run As* като указваш кое AVD устройство да се използва. Би трябвало да се стартира прозорец с Андроид емулатора и приложението да се инсталира вътре. Емулаторът е бавничък и отнема време докато зареди.

![screen shot 2015-05-18 at 13 53 05](https://cloud.githubusercontent.com/assets/547597/7680321/7fc4e5fa-fd65-11e4-9fb8-2df9b15f32cb.png)

**Comment by Tsvetoslav88** [comment]
Здравей,

Инсталирах си няколко виртуални устройства, като според мен имам проблем да стартирам, такива, които са на Android 4.4.2.(или може аз нещо да не съм сложил както трябва). Успешно стартирах Android 4.0.3.
![avd](https://cloud.githubusercontent.com/assets/8929789/7744579/54494eb2-ffad-11e4-93aa-9295aff06e52.jpg)
Не знам дали не е много стара версия и дали ще свърши работа, но пробвах да стартирам проеката и ми излезе:
![myglob](https://cloud.githubusercontent.com/assets/8929789/7744588/773943aa-ffad-11e4-8543-cece79580c52.jpg)


Поздрави.

**Comment by petarov** [comment]
Здравей,

Да, това е началният екран. До тук всичко добре! Може да си добавиш профил (телефон) и да провериш дали основната функционалност работи. Профилът е същият, с който се влиза на my.telenor.bg. Надявам се имаш Теленор номер?

**Comment by Tsvetoslav88** [comment]
Здравей.

За съжаление телефонният ми номер на telenor е на ваучер и не знам дали мога да тествам всичките функций, като не съм на сметка. Добавих си номера+парола и на Status ми даде: 
![status](https://cloud.githubusercontent.com/assets/8929789/7789029/1f856f98-025b-11e5-90ea-460591a3c497.jpg)
След като отидох на "Actions...->Check invoice" ми даде:
![invoice](https://cloud.githubusercontent.com/assets/8929789/7789033/3981fb78-025b-11e5-8e19-59fc3614c5bf.jpg)

Поздрави.

**Comment by petarov** [comment]
Привет,

Не съм пробвал дали може да се ползва системата им с ваучер, но според мен би трябвало да е ОК. Ако пробваш да влезеш с потребителят и паролата си директно на сайта им, то възниква ли някаква грешка?

По-принцип това е едно от нещата, които приложението не поддържа и което ще е чудесно да намерим начин да добавим, а именно въвеждане на CAPTCHA код ;).

**Comment by Tsvetoslav88** [comment]
Здравей,

Мисля, че профила, който съм създал не ми се е записал в базата на telenor, защото, като направя опит да се впиша ми дава: Въвели сте грешни данни за вход в портала! Моля, опитайте отново, като проверите дали въвеждате малки или големи букви, на кирилица или на латиница.
Имам чувството, че това, което го правя се отразява само при мен локалано, но ми е нужно малко съдействие от твоя страна, за да видя какво се случва :)

Поздрави.

**Comment by petarov** [comment]
Здравей Цецо,
Да преместим разговора тук в [този чат](https://gitter.im/petarov/myglob) и да обсъдим по детайлно там как можем да процедираме.

**Comment by Tsvetoslav88** [comment]
Здравей,
ОК, писах на другия чат.
Поздрави!
